"""A small, curated quick-reference of common Linux commands for the F1 helper.

Deliberately NOT comprehensive — the Pareto set: the commands people reach for
daily, with the flag combinations that are easy to forget. Each entry is
{name, summary, notes, examples:[(what, command), ...]}. `notes` may mention
distro differences (apt vs dnf, ss vs netstat, etc.)."""

COMMANDS = [
    {"name": "ls", "summary": "list directory contents", "notes": "",
     "examples": [("long, human sizes, hidden", "ls -lah"),
                  ("newest last (sort by mtime, reversed)", "ls -ltr"),
                  ("only directories", "ls -d */"),
                  ("sort by size, largest first", "ls -lSh")]},
    {"name": "cd", "summary": "change directory", "notes": "shell builtin",
     "examples": [("previous directory (toggle)", "cd -"),
                  ("home", "cd"),
                  ("up two levels", "cd ../..")]},
    {"name": "cp", "summary": "copy files and directories", "notes": "",
     "examples": [("recursive, preserve attrs", "cp -a src/ dst/"),
                  ("only if newer / missing", "cp -u a b"),
                  ("keep a backup of overwritten files", "cp --backup=numbered a b")]},
    {"name": "mv", "summary": "move / rename", "notes": "",
     "examples": [("prompt before overwrite", "mv -i a b"),
                  ("no-clobber (never overwrite)", "mv -n a b")]},
    {"name": "rm", "summary": "remove files/directories", "notes": "there is no undo",
     "examples": [("recursive + force", "rm -rf dir/"),
                  ("prompt once for many files", "rm -I *.log"),
                  ("end-of-options, for a file named -x", "rm -- -x")]},
    {"name": "mkdir", "summary": "make directories", "notes": "",
     "examples": [("create parents as needed", "mkdir -p a/b/c"),
                  ("with explicit mode", "mkdir -m 700 secret")]},
    {"name": "ln", "summary": "make links", "notes": "default is a hard link",
     "examples": [("symbolic link", "ln -s /path/to/target linkname"),
                  ("force-replace an existing symlink", "ln -sf newtarget linkname")]},
    {"name": "find", "summary": "search a directory tree", "notes": "",
     "examples": [("by name (glob)", "find . -name '*.conf'"),
                  ("by name, case-insensitive", "find . -iname '*.log'"),
                  ("files over 100 MB", "find / -type f -size +100M"),
                  ("modified in last 2 days", "find . -mtime -2"),
                  ("run a command per match (safe)", "find . -name '*.tmp' -delete"),
                  ("exec with xargs for speed", "find . -name '*.o' -print0 | xargs -0 rm")]},
    {"name": "grep", "summary": "search text with patterns", "notes": "",
     "examples": [("recursive, line numbers", "grep -rn 'needle' ."),
                  ("case-insensitive, whole word", "grep -iw error log"),
                  ("show 3 lines of context", "grep -C3 'panic' file"),
                  ("invert (lines NOT matching)", "grep -v '^#' config"),
                  ("only the matching part", "grep -o 'id=[0-9]*' file"),
                  ("extended regex", "grep -E 'foo|bar' file")]},
    {"name": "sed", "summary": "stream editor (substitution)", "notes": "-i edits in place",
     "examples": [("replace first per line", "sed 's/old/new/' f"),
                  ("replace all, in place + backup", "sed -i.bak 's/old/new/g' f"),
                  ("delete lines matching", "sed '/^#/d' f"),
                  ("print only lines 10-20", "sed -n '10,20p' f")]},
    {"name": "awk", "summary": "field-based text processing", "notes": "",
     "examples": [("print column 2", "awk '{print $2}' f"),
                  ("sum a column", "awk '{s+=$1} END{print s}' f"),
                  ("custom field separator", "awk -F: '{print $1}' /etc/passwd"),
                  ("filter rows by a column", "awk '$3 > 100' f")]},
    {"name": "sort", "summary": "sort lines", "notes": "",
     "examples": [("numeric, descending", "sort -nr f"),
                  ("by column 2, numeric", "sort -k2 -n f"),
                  ("unique after sort", "sort -u f"),
                  ("human sizes (1K, 2M)", "sort -h f")]},
    {"name": "uniq", "summary": "collapse/count adjacent duplicate lines", "notes": "input must be sorted",
     "examples": [("count occurrences", "sort f | uniq -c"),
                  ("only duplicated lines", "sort f | uniq -d"),
                  ("top 10 most frequent", "sort f | uniq -c | sort -nr | head")]},
    {"name": "cut", "summary": "select columns/characters", "notes": "",
     "examples": [("fields 1 and 3, tab-delimited", "cut -f1,3 f"),
                  ("by delimiter", "cut -d: -f1 /etc/passwd"),
                  ("characters 1-10", "cut -c1-10 f")]},
    {"name": "tr", "summary": "translate/delete characters", "notes": "",
     "examples": [("lower to upper", "tr a-z A-Z"),
                  ("squeeze repeats", "tr -s ' '"),
                  ("delete characters", "tr -d '\\r' < dosfile")]},
    {"name": "xargs", "summary": "build command lines from input", "notes": "pair with -print0/-0 for odd names",
     "examples": [("one arg per line, run cmd", "cat list | xargs -n1 echo"),
                  ("null-delimited (safe)", "find . -name '*.log' -print0 | xargs -0 rm"),
                  ("parallel, 4 at a time", "xargs -P4 -n1 gzip < list")]},
    {"name": "head", "summary": "first lines/bytes", "notes": "",
     "examples": [("first 20 lines", "head -n20 f"),
                  ("all but the last line", "head -n-1 f")]},
    {"name": "tail", "summary": "last lines; follow a growing file", "notes": "",
     "examples": [("follow (live log)", "tail -f /var/log/syslog"),
                  ("follow even across rotation", "tail -F app.log"),
                  ("from line 100 to end", "tail -n+100 f")]},
    {"name": "wc", "summary": "count lines/words/bytes", "notes": "",
     "examples": [("line count", "wc -l f"),
                  ("longest line length", "wc -L f")]},
    {"name": "tar", "summary": "archive files", "notes": "z=gzip, j=bzip2, J=xz",
     "examples": [("create gzip archive", "tar czf out.tgz dir/"),
                  ("extract", "tar xzf out.tgz"),
                  ("list contents", "tar tzf out.tgz"),
                  ("extract to a directory", "tar xzf out.tgz -C /dest")]},
    {"name": "rsync", "summary": "fast incremental copy/sync (local or over ssh)", "notes": "trailing slash on src matters",
     "examples": [("mirror, preserve, progress", "rsync -aP src/ dst/"),
                  ("over ssh", "rsync -aP src/ user@host:/path/"),
                  ("delete extras on dest (mirror)", "rsync -aP --delete src/ dst/"),
                  ("dry run first", "rsync -aP --delete --dry-run src/ dst/")]},
    {"name": "chmod", "summary": "change permissions", "notes": "",
     "examples": [("rwx for owner, rx for rest", "chmod 755 f"),
                  ("add execute for all", "chmod +x script.sh"),
                  ("recursive, dirs only +x", "chmod -R u+rwX,go+rX dir")]},
    {"name": "chown", "summary": "change owner/group", "notes": "",
     "examples": [("owner and group", "chown user:group f"),
                  ("recursive", "chown -R www-data: /var/www")]},
    {"name": "df", "summary": "disk space by filesystem", "notes": "",
     "examples": [("human sizes", "df -h"),
                  ("inodes (when 'disk full' but space free)", "df -i")]},
    {"name": "du", "summary": "disk usage by path", "notes": "",
     "examples": [("total for a dir", "du -sh dir/"),
                  ("biggest subdirs here", "du -h --max-depth=1 | sort -h"),
                  ("top 10 largest anywhere", "du -ah . | sort -h | tail")]},
    {"name": "free", "summary": "memory usage", "notes": "",
     "examples": [("human readable", "free -h"),
                  ("refresh every 2s", "free -h -s2")]},
    {"name": "ps", "summary": "process snapshot", "notes": "",
     "examples": [("everything, full", "ps aux"),
                  ("tree view", "ps auxf"),
                  ("sort by memory", "ps aux --sort=-%mem | head")]},
    {"name": "top", "summary": "live process monitor", "notes": "htop is nicer if installed",
     "examples": [("sort by memory: press", "top  (then Shift+M)"),
                  ("one user", "top -u www-data")]},
    {"name": "kill", "summary": "signal a process by PID", "notes": "pkill/killall match by name",
     "examples": [("graceful then forceful", "kill PID   # then  kill -9 PID"),
                  ("by name", "pkill -f myscript.py"),
                  ("list signal names", "kill -l")]},
    {"name": "systemctl", "summary": "manage systemd services", "notes": "most modern distros; not on MX's sysVinit by default",
     "examples": [("status", "systemctl status nginx"),
                  ("start/stop/restart", "systemctl restart nginx"),
                  ("enable at boot", "systemctl enable --now nginx"),
                  ("what failed", "systemctl --failed")]},
    {"name": "journalctl", "summary": "query the systemd journal", "notes": "systemd systems",
     "examples": [("follow a unit", "journalctl -u ssh -f"),
                  ("since 10 min ago", "journalctl --since '-10 min'"),
                  ("this boot, errors+", "journalctl -b -p err"),
                  ("kernel messages", "journalctl -k")]},
    {"name": "ss", "summary": "socket/port listing (replaces netstat)", "notes": "iproute2; use ss over netstat",
     "examples": [("listening TCP + process", "ss -tlnp"),
                  ("all established", "ss -tanp"),
                  ("who's on port 443", "ss -tlnp 'sport = :443'")]},
    {"name": "ip", "summary": "interfaces, addresses, routes (replaces ifconfig)", "notes": "iproute2",
     "examples": [("addresses", "ip a"),
                  ("routes", "ip r"),
                  ("bring an interface up", "ip link set eth0 up")]},
    {"name": "ssh", "summary": "secure shell", "notes": "~/.ssh/config holds host shortcuts",
     "examples": [("non-standard port", "ssh -p 2222 user@host"),
                  ("run one command", "ssh host 'uptime'"),
                  ("jump through a bastion", "ssh -J bastion user@internal"),
                  ("local port forward", "ssh -L 8080:localhost:80 host")]},
    {"name": "scp", "summary": "copy files over ssh", "notes": "rsync is better for big/repeat copies",
     "examples": [("to remote", "scp file user@host:/path/"),
                  ("from remote, recursive", "scp -r user@host:/path/ ."),
                  ("non-standard port (capital P)", "scp -P 2222 file host:/path/")]},
    {"name": "curl", "summary": "transfer URLs", "notes": "",
     "examples": [("save to file", "curl -O https://x/y.tgz"),
                  ("follow redirects, show errors", "curl -fSL url"),
                  ("headers only", "curl -I url"),
                  ("POST JSON", "curl -X POST -H 'Content-Type: application/json' -d '{}' url")]},
    {"name": "wget", "summary": "download files", "notes": "",
     "examples": [("resume a partial download", "wget -c url"),
                  ("mirror a site", "wget -mkEpnp url")]},
    {"name": "dig", "summary": "DNS lookups", "notes": "host/nslookup are simpler alternatives",
     "examples": [("short answer", "dig +short example.com"),
                  ("specific record", "dig example.com MX"),
                  ("via a specific resolver", "dig @1.1.1.1 example.com")]},
    {"name": "ufw", "summary": "simple firewall (Debian/Ubuntu/MX)", "notes": "firewalld on Fedora/RHEL",
     "examples": [("allow a port", "ufw allow 22/tcp"),
                  ("allow from an IP", "ufw allow from 1.2.3.4"),
                  ("numbered list", "ufw status numbered"),
                  ("delete a rule", "ufw delete 3")]},
    {"name": "crontab", "summary": "scheduled jobs", "notes": "fields: min hour dom mon dow",
     "examples": [("edit your crontab", "crontab -e"),
                  ("list", "crontab -l"),
                  ("example: 2am daily", "0 2 * * *  /path/script.sh"),
                  ("every 5 minutes", "*/5 * * * *  cmd")]},
    {"name": "apt", "summary": "packages on Debian/Ubuntu/MX", "notes": "dnf/yum on Fedora/RHEL",
     "examples": [("update + upgrade", "apt update && apt upgrade"),
                  ("install", "apt install pkg"),
                  ("search", "apt search term"),
                  ("which package owns a file", "dpkg -S /usr/bin/ssh")]},
    {"name": "dnf", "summary": "packages on Fedora/RHEL", "notes": "yum is the older name; apt on Debian/Ubuntu",
     "examples": [("install", "dnf install pkg"),
                  ("upgrade all", "dnf upgrade"),
                  ("what provides a file", "dnf provides /usr/bin/ss")]},
    {"name": "git", "summary": "version control", "notes": "",
     "examples": [("status + short branch", "git status -sb"),
                  ("stage + commit", "git commit -am 'msg'"),
                  ("last 5, one line", "git log --oneline -5"),
                  ("discard local changes to a file", "git checkout -- file"),
                  ("what changed", "git diff")]},
    {"name": "docker", "summary": "containers", "notes": "",
     "examples": [("running containers", "docker ps"),
                  ("shell into one", "docker exec -it NAME bash"),
                  ("follow logs", "docker logs -f NAME"),
                  ("clean up unused", "docker system prune")]},
    {"name": "mysql", "summary": "MySQL/MariaDB client", "notes": "mysqldump for backups",
     "examples": [("connect", "mysql -u root -p dbname"),
                  ("run one query", "mysql -e 'SHOW DATABASES'"),
                  ("dump a database", "mysqldump db > db.sql"),
                  ("restore", "mysql db < db.sql")]},
    {"name": "tmux", "summary": "terminal multiplexer (persistent sessions)", "notes": "prefix is Ctrl-b",
     "examples": [("new named session", "tmux new -s work"),
                  ("detach", "Ctrl-b d"),
                  ("reattach", "tmux attach -t work"),
                  ("list sessions", "tmux ls")]},
    {"name": "watch", "summary": "re-run a command periodically", "notes": "",
     "examples": [("every 2s (default)", "watch df -h"),
                  ("every 5s, highlight changes", "watch -n5 -d 'ss -s'")]},
    {"name": "stat", "summary": "file metadata", "notes": "",
     "examples": [("full info", "stat f"),
                  ("just the octal mode", "stat -c '%a %n' f")]},
    {"name": "lsof", "summary": "list open files / who holds them", "notes": "",
     "examples": [("what's using a port", "lsof -i :80"),
                  ("files open under a dir", "lsof +D /var/log"),
                  ("deleted-but-held files", "lsof +L1")]},
    {"name": "history", "summary": "shell command history", "notes": "shell builtin; sshTIK's F2 searches it",
     "examples": [("re-run command number", "!123"),
                  ("re-run last", "!!"),
                  ("search interactively", "Ctrl-r")]},
]
